services:
  postgresql:
    image: postgres:latest
    environment:
      POSTGRES_USER: kris
      POSTGRES_PASSWORD: ""
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: kris
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  kafka:
    image: confluentinc/cp-kafka:latest
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:29092
    ports:
      - "29092:29092"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.0
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"

  logstash:
    image: docker.elastic.co/logstash/logstash:8.7.0
    ports:
      - "5044:5044"
  
  kibana:
    image: docker.elastic.co/kibana/kibana:8.7.0
    ports:
      - "5601:5601"

  app:
    image: springboot-app
    depends_on:
      - postgresql
      - kafka
      - redis
      - elasticsearch
      - logstash
      - kibana
    ports:
      - "8080:8080"
    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql:5432/kris
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/kris
      SPRING_DATASOURCE_USERNAME: kris
      SPRING_DATASOURCE_PASSWORD: ""

volumes:
  pgdata:
