spring:
  datasource:
    postgres:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/ecommerce
      username: kris
      password: ''
    mysql:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/ecommerce  # 修改为你的 MySQL 数据库名
      username: root  # 修改为你的 MySQL 用户名
      ipassword: ''   # 修改为你的 MySQL 密码

  jpa:
    postgres:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
    mysql:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect

  data:
    redis:
      host: localhost
      port: 6379
      password: ''

  cassandra:
    contact-points: localhost
    port: 9042
    keyspace-name: ecommerce
    schema-action: create-if-not-exists

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  kafka:
    bootstrap-servers: localhost:9092
    properties:
      group.id: "cdc-consumer-group"
      enable.auto.commit: false
      auto.offset.reset: earliest
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer



#ratelimiter:
#  max-requests: 5          # 每个时间窗口允许的最大请求数
#  time-window-in-seconds: 10 # 时间窗口大小（秒）

